[package]
name = "crust"
version = "0.2.0"
edition = "2024"

[lib]
name = "crust"
path = "src/lib.rs"

[[bin]]
name = "crust"
path = "src/main.rs"

[[bin]]
name = "sim"
path = "src/bin/sim.rs"
required-features = ["simulator"]

[features]
simulator = ["dep:embedded-graphics-simulator"]

[dependencies]
ssd1306 = "0.9"
embedded-graphics = "0.8"
display-interface = "0.5"
embedded-graphics-simulator = { version = "0.5", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
linux-embedded-hal = "0.4"
