[general]
framerate = 30
bars = 16
bar_width = 1
bar_spacing = 0
sensitivity = 50

[input]
method = fifo
source = /tmp/mpd.fifo
sample_rate = 44100
sample_bits = 16
channels = 2

[output]
method = raw
raw_target = /tmp/cava.fifo
bit_format = 16bit
